### ISSUE TITLE
Deprecation warning in Electron v7

### ISSUE THREAD

**Issue by jacobq** [pichfl/electron-protocol-serve#9]
The snippet below triggers a deprecation warning in Electron v7.x like this: `(node:645632) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.`

https://github.com/pichfl/electron-protocol-serve/blob/0e979cd49383f15b5eedc7399edb5cad9585ab2e/index.js#L42-L46

See https://github.com/electron/electron/blob/7-0-x/docs/api/breaking-changes-ns.md#planned-breaking-api-changes

**Comment by RobbieTheWagner** [comment]
Would it be possible to get a new version released with these changes? I think I'm seeing this issue too.

**Comment by bendemboski** [comment]
Yeah, I can cut a release. We haven't released in quite a while, so while there are only a few changes, some are years old! I'd like to run a quick sanity check using yarn resolutions (or yarn link or whatever) to run an `ember-electron` project against the latest master of `electron-protocol-serve` before releasing. I probably won't be able to get to that for a couple of days (deep in some stuff right now), but if you or @jacobq has a few minutes to run that experiment and report back, I can snap a release right away.

**Comment by RobbieTheWagner** [comment]
@bendemboski I totally forgot about this. Did you still need someone to try testing master?

**Comment by bendemboski** [comment]
Yeah, I haven't touched it since this convo

**Comment by RobbieTheWagner** [comment]
Is `yarn link electron-protocol-serve` the only thing we should need to do or do I need to link it inside ember-electron and do a nested link?

**Comment by bendemboski** [comment]
Ack, sorry, this fell down my inbox and I forgot about it. Yeah, the only place it's used is where you set it up in your `electron-app/index.js` (blueprint-generated), where it's required as a normal node module, so `cd electron-app; yarn link electron-protocol-serve` should be sufficient.

**Comment by RobbieTheWagner** [comment]
@bendemboski I did that and it seemed to work fine

**Comment by bendemboski** [comment]
Cool, I'll cut a release in the next day or two then. Thanks!
